package cmd

import (
	"fmt"

	"github.com/aprksy/knitknot/pkg/graph"
)

func seedSampleData(engine *graph.GraphEngine) {
	customer_1, _ := engine.AddNode("customer", map[string]any{"name": "Jacqueline Lemke", "username": "floracer", "email": "jacquelinejlemke@superrito.com", "phone": "859-508-3143", "age": "51", "gender": "female", "city": "Lexington", "expense": "6210", "trx": "8"})
	customer_2, _ := engine.AddNode("customer", map[string]any{"name": "Kristine Vosburg", "username": "scourter", "email": "kristinecvosburg@teleworm.us", "phone": "831-783-0478", "age": "59", "gender": "female", "city": "Salinas", "expense": "3280", "trx": "15"})
	customer_3, _ := engine.AddNode("customer", map[string]any{"name": "Nancy Crawford", "username": "leoutitend", "email": "nancypcrawford@gustr.com", "phone": "469-454-5211", "age": "39", "gender": "female", "city": "Frisco", "expense": "4680", "trx": "12"})
	customer_4, _ := engine.AddNode("customer", map[string]any{"name": "Lindsay Snead", "username": "weree1979", "email": "lindsaypsnead@gustr.com", "phone": "510-489-4556", "age": "45", "gender": "female", "city": "Union City", "expense": "5040", "trx": "15"})
	customer_5, _ := engine.AddNode("customer", map[string]any{"name": "Lemuel Olguin", "username": "begre1985", "email": "lemuelrolguin@einrot.com", "phone": "214-765-7503", "age": "40", "gender": "male", "city": "Dallas", "expense": "3250", "trx": "3"})
	customer_6, _ := engine.AddNode("customer", map[string]any{"name": "Zachary Patterson", "username": "incents", "email": "zacharyfpatterson@superrito.com", "phone": "541-453-0393", "age": "40", "gender": "male", "city": "Blodgett", "expense": "4360", "trx": "18"})
	customer_7, _ := engine.AddNode("customer", map[string]any{"name": "Jeanne Speirs", "username": "forgoin", "email": "jeannetspeirs@einrot.com", "phone": "410-313-6123", "age": "21", "gender": "female", "city": "Ellicott City", "expense": "3200", "trx": "12"})
	customer_8, _ := engine.AddNode("customer", map[string]any{"name": "Daniel Wright", "username": "anots1988", "email": "daniellwright@jourrapide.com", "phone": "972-927-2964", "age": "37", "gender": "male", "city": "Richardson", "expense": "3230", "trx": "17"})
	customer_9, _ := engine.AddNode("customer", map[string]any{"name": "Susan Haynes", "username": "yess1983", "email": "susanshaynes@teleworm.us", "phone": "507-583-0433", "age": "42", "gender": "female", "city": "Blooming Prairie", "expense": "4090", "trx": "12"})
	customer_10, _ := engine.AddNode("customer", map[string]any{"name": "Victoria Smith", "username": "yeted1972", "email": "victoriapsmith@jourrapide.com", "phone": "540-864-2974", "age": "53", "gender": "female", "city": "New Castle", "expense": "3640", "trx": "18"})

	channel_1, _ := engine.AddNode("channel", map[string]any{"name": "Marketplace"})
	channel_2, _ := engine.AddNode("channel", map[string]any{"name": "Web app"})
	channel_3, _ := engine.AddNode("channel", map[string]any{"name": "Mobile app"})
	channel_4, _ := engine.AddNode("channel", map[string]any{"name": "Local store"})
	channel_5, _ := engine.AddNode("channel", map[string]any{"name": "Bazzar"})

	commodity_1, _ := engine.AddNode("commodity", map[string]any{"name": "Grocery"})
	commodity_2, _ := engine.AddNode("commodity", map[string]any{"name": "Fashion"})
	commodity_3, _ := engine.AddNode("commodity", map[string]any{"name": "FnB"})
	commodity_4, _ := engine.AddNode("commodity", map[string]any{"name": "Gadget"})
	commodity_5, _ := engine.AddNode("commodity", map[string]any{"name": "Computer"})
	commodity_6, _ := engine.AddNode("commodity", map[string]any{"name": "Automobile"})
	commodity_7, _ := engine.AddNode("commodity", map[string]any{"name": "Sport"})
	commodity_8, _ := engine.AddNode("commodity", map[string]any{"name": "Household"})
	commodity_9, _ := engine.AddNode("commodity", map[string]any{"name": "Tools"})
	commodity_10, _ := engine.AddNode("commodity", map[string]any{"name": "Electronics"})
	commodity_11, _ := engine.AddNode("commodity", map[string]any{"name": "Gaming"})
	commodity_12, _ := engine.AddNode("commodity", map[string]any{"name": "Digital Products"})
	commodity_13, _ := engine.AddNode("commodity", map[string]any{"name": "Health & Beauty"})
	commodity_14, _ := engine.AddNode("commodity", map[string]any{"name": "Hobby"})
	commodity_15, _ := engine.AddNode("commodity", map[string]any{"name": "Book"})
	commodity_16, _ := engine.AddNode("commodity", map[string]any{"name": "Toy"})
	commodity_17, _ := engine.AddNode("commodity", map[string]any{"name": "Industrial"})
	commodity_18, _ := engine.AddNode("commodity", map[string]any{"name": "Stationary"})
	commodity_19, _ := engine.AddNode("commodity", map[string]any{"name": "Travel & Tickets"})
	commodity_20, _ := engine.AddNode("commodity", map[string]any{"name": "Entertainment"})
	commodity_21, _ := engine.AddNode("commodity", map[string]any{"name": "Educational"})
	commodity_22, _ := engine.AddNode("commodity", map[string]any{"name": "Raw Products"})
	commodity_23, _ := engine.AddNode("commodity", map[string]any{"name": "Services"})

	payment_method_1, _ := engine.AddNode("payment_method", map[string]any{"name": "Bank Transfer"})
	payment_method_2, _ := engine.AddNode("payment_method", map[string]any{"name": "Credit Card"})
	payment_method_3, _ := engine.AddNode("payment_method", map[string]any{"name": "QRsystem"})
	payment_method_4, _ := engine.AddNode("payment_method", map[string]any{"name": "Cash"})
	payment_method_5, _ := engine.AddNode("payment_method", map[string]any{"name": "PayPal"})
	payment_method_6, _ := engine.AddNode("payment_method", map[string]any{"name": "PooplePay"})

	err := engine.AddEdge(customer_1, channel_1, "make_purchase_in", map[string]any{"trx_count": 1, "trx_amount": 1499})

	if err != nil {
		fmt.Println(err.Error())
	}
	engine.AddEdge(customer_1, channel_2, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 1590})
	engine.AddEdge(customer_1, channel_4, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 1551})
	engine.AddEdge(customer_1, channel_5, "make_purchase_in", map[string]any{"trx_count": 3, "trx_amount": 1570})
	engine.AddEdge(customer_2, channel_1, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 643})
	engine.AddEdge(customer_2, channel_2, "make_purchase_in", map[string]any{"trx_count": 3, "trx_amount": 665})
	engine.AddEdge(customer_2, channel_3, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 665})
	engine.AddEdge(customer_2, channel_4, "make_purchase_in", map[string]any{"trx_count": 5, "trx_amount": 649})
	engine.AddEdge(customer_2, channel_5, "make_purchase_in", map[string]any{"trx_count": 3, "trx_amount": 658})
	engine.AddEdge(customer_3, channel_1, "make_purchase_in", map[string]any{"trx_count": 1, "trx_amount": 939})
	engine.AddEdge(customer_3, channel_2, "make_purchase_in", map[string]any{"trx_count": 3, "trx_amount": 947})
	engine.AddEdge(customer_3, channel_3, "make_purchase_in", map[string]any{"trx_count": 4, "trx_amount": 928})
	engine.AddEdge(customer_3, channel_4, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 930})
	engine.AddEdge(customer_3, channel_5, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 936})
	engine.AddEdge(customer_4, channel_1, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 1196})
	engine.AddEdge(customer_4, channel_3, "make_purchase_in", map[string]any{"trx_count": 7, "trx_amount": 1283})
	engine.AddEdge(customer_4, channel_4, "make_purchase_in", map[string]any{"trx_count": 4, "trx_amount": 1276})
	engine.AddEdge(customer_4, channel_5, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 1285})
	engine.AddEdge(customer_5, channel_1, "make_purchase_in", map[string]any{"trx_count": 1, "trx_amount": 1681})
	engine.AddEdge(customer_5, channel_2, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 1569})
	engine.AddEdge(customer_6, channel_1, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 865})
	engine.AddEdge(customer_6, channel_2, "make_purchase_in", map[string]any{"trx_count": 4, "trx_amount": 887})
	engine.AddEdge(customer_6, channel_3, "make_purchase_in", map[string]any{"trx_count": 1, "trx_amount": 859})
	engine.AddEdge(customer_6, channel_4, "make_purchase_in", map[string]any{"trx_count": 7, "trx_amount": 883})
	engine.AddEdge(customer_6, channel_5, "make_purchase_in", map[string]any{"trx_count": 4, "trx_amount": 866})
	engine.AddEdge(customer_7, channel_1, "make_purchase_in", map[string]any{"trx_count": 1, "trx_amount": 643})
	engine.AddEdge(customer_7, channel_2, "make_purchase_in", map[string]any{"trx_count": 3, "trx_amount": 651})
	engine.AddEdge(customer_7, channel_3, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 662})
	engine.AddEdge(customer_7, channel_4, "make_purchase_in", map[string]any{"trx_count": 4, "trx_amount": 635})
	engine.AddEdge(customer_7, channel_5, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 609})
	engine.AddEdge(customer_8, channel_1, "make_purchase_in", map[string]any{"trx_count": 4, "trx_amount": 672})
	engine.AddEdge(customer_8, channel_2, "make_purchase_in", map[string]any{"trx_count": 3, "trx_amount": 617})
	engine.AddEdge(customer_8, channel_3, "make_purchase_in", map[string]any{"trx_count": 3, "trx_amount": 639})
	engine.AddEdge(customer_8, channel_4, "make_purchase_in", map[string]any{"trx_count": 3, "trx_amount": 646})
	engine.AddEdge(customer_8, channel_5, "make_purchase_in", map[string]any{"trx_count": 4, "trx_amount": 656})
	engine.AddEdge(customer_9, channel_1, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 859})
	engine.AddEdge(customer_9, channel_2, "make_purchase_in", map[string]any{"trx_count": 5, "trx_amount": 803})
	engine.AddEdge(customer_9, channel_3, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 804})
	engine.AddEdge(customer_9, channel_4, "make_purchase_in", map[string]any{"trx_count": 2, "trx_amount": 804})
	engine.AddEdge(customer_9, channel_5, "make_purchase_in", map[string]any{"trx_count": 1, "trx_amount": 820})
	engine.AddEdge(customer_10, channel_1, "make_purchase_in", map[string]any{"trx_count": 1, "trx_amount": 703})
	engine.AddEdge(customer_10, channel_2, "make_purchase_in", map[string]any{"trx_count": 3, "trx_amount": 717})
	engine.AddEdge(customer_10, channel_3, "make_purchase_in", map[string]any{"trx_count": 7, "trx_amount": 725})
	engine.AddEdge(customer_10, channel_4, "make_purchase_in", map[string]any{"trx_count": 4, "trx_amount": 782})
	engine.AddEdge(customer_10, channel_5, "make_purchase_in", map[string]any{"trx_count": 3, "trx_amount": 713})

	engine.AddEdge(customer_1, payment_method_1, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 2069})
	engine.AddEdge(customer_1, payment_method_2, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 2026})
	engine.AddEdge(customer_1, payment_method_6, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 2115})
	engine.AddEdge(customer_2, payment_method_2, "make_payment_using", map[string]any{"trx_count": 4, "trx_amount": 620})
	engine.AddEdge(customer_2, payment_method_3, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 654})
	engine.AddEdge(customer_2, payment_method_4, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 720})
	engine.AddEdge(customer_2, payment_method_5, "make_payment_using", map[string]any{"trx_count": 4, "trx_amount": 632})
	engine.AddEdge(customer_2, payment_method_6, "make_payment_using", map[string]any{"trx_count": 1, "trx_amount": 654})
	engine.AddEdge(customer_3, payment_method_1, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 752})
	engine.AddEdge(customer_3, payment_method_2, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 773})
	engine.AddEdge(customer_3, payment_method_3, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 788})
	engine.AddEdge(customer_3, payment_method_4, "make_payment_using", map[string]any{"trx_count": 1, "trx_amount": 795})
	engine.AddEdge(customer_3, payment_method_5, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 789})
	engine.AddEdge(customer_3, payment_method_6, "make_payment_using", map[string]any{"trx_count": 1, "trx_amount": 783})
	engine.AddEdge(customer_4, payment_method_1, "make_payment_using", map[string]any{"trx_count": 4, "trx_amount": 784})
	engine.AddEdge(customer_4, payment_method_2, "make_payment_using", map[string]any{"trx_count": 5, "trx_amount": 849})
	engine.AddEdge(customer_4, payment_method_3, "make_payment_using", map[string]any{"trx_count": 1, "trx_amount": 814})
	engine.AddEdge(customer_4, payment_method_4, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 913})
	engine.AddEdge(customer_4, payment_method_5, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 862})
	engine.AddEdge(customer_4, payment_method_6, "make_payment_using", map[string]any{"trx_count": 1, "trx_amount": 818})
	engine.AddEdge(customer_5, payment_method_1, "make_payment_using", map[string]any{"trx_count": 1, "trx_amount": 1646})
	engine.AddEdge(customer_5, payment_method_5, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 1604})
	engine.AddEdge(customer_6, payment_method_1, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 876})
	engine.AddEdge(customer_6, payment_method_2, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 913})
	engine.AddEdge(customer_6, payment_method_3, "make_payment_using", map[string]any{"trx_count": 4, "trx_amount": 874})
	engine.AddEdge(customer_6, payment_method_5, "make_payment_using", map[string]any{"trx_count": 4, "trx_amount": 842})
	engine.AddEdge(customer_6, payment_method_6, "make_payment_using", map[string]any{"trx_count": 5, "trx_amount": 855})
	engine.AddEdge(customer_7, payment_method_1, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 520})
	engine.AddEdge(customer_7, payment_method_2, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 533})
	engine.AddEdge(customer_7, payment_method_3, "make_payment_using", map[string]any{"trx_count": 1, "trx_amount": 544})
	engine.AddEdge(customer_7, payment_method_4, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 539})
	engine.AddEdge(customer_7, payment_method_5, "make_payment_using", map[string]any{"trx_count": 1, "trx_amount": 575})
	engine.AddEdge(customer_7, payment_method_6, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 489})
	engine.AddEdge(customer_8, payment_method_1, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 547})
	engine.AddEdge(customer_8, payment_method_2, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 510})
	engine.AddEdge(customer_8, payment_method_3, "make_payment_using", map[string]any{"trx_count": 1, "trx_amount": 579})
	engine.AddEdge(customer_8, payment_method_4, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 548})
	engine.AddEdge(customer_8, payment_method_5, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 540})
	engine.AddEdge(customer_8, payment_method_6, "make_payment_using", map[string]any{"trx_count": 6, "trx_amount": 506})
	engine.AddEdge(customer_9, payment_method_2, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 778})
	engine.AddEdge(customer_9, payment_method_3, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 810})
	engine.AddEdge(customer_9, payment_method_4, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 836})
	engine.AddEdge(customer_9, payment_method_5, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 826})
	engine.AddEdge(customer_9, payment_method_6, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 840})
	engine.AddEdge(customer_10, payment_method_1, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 610})
	engine.AddEdge(customer_10, payment_method_2, "make_payment_using", map[string]any{"trx_count": 4, "trx_amount": 612})
	engine.AddEdge(customer_10, payment_method_3, "make_payment_using", map[string]any{"trx_count": 2, "trx_amount": 591})
	engine.AddEdge(customer_10, payment_method_4, "make_payment_using", map[string]any{"trx_count": 3, "trx_amount": 575})
	engine.AddEdge(customer_10, payment_method_5, "make_payment_using", map[string]any{"trx_count": 1, "trx_amount": 641})
	engine.AddEdge(customer_10, payment_method_6, "make_payment_using", map[string]any{"trx_count": 5, "trx_amount": 611})

	engine.AddEdge(customer_1, commodity_3, "purchase", map[string]any{"trx_count": 1, "trx_amount": 788})
	engine.AddEdge(customer_1, commodity_7, "purchase", map[string]any{"trx_count": 1, "trx_amount": 747})
	engine.AddEdge(customer_1, commodity_8, "purchase", map[string]any{"trx_count": 1, "trx_amount": 746})
	engine.AddEdge(customer_1, commodity_9, "purchase", map[string]any{"trx_count": 1, "trx_amount": 735})
	engine.AddEdge(customer_1, commodity_11, "purchase", map[string]any{"trx_count": 1, "trx_amount": 813})
	engine.AddEdge(customer_1, commodity_12, "purchase", map[string]any{"trx_count": 1, "trx_amount": 770})
	engine.AddEdge(customer_1, commodity_13, "purchase", map[string]any{"trx_count": 1, "trx_amount": 818})
	engine.AddEdge(customer_1, commodity_22, "purchase", map[string]any{"trx_count": 1, "trx_amount": 793})
	engine.AddEdge(customer_2, commodity_1, "purchase", map[string]any{"trx_count": 1, "trx_amount": 306})
	engine.AddEdge(customer_2, commodity_2, "purchase", map[string]any{"trx_count": 2, "trx_amount": 263})
	engine.AddEdge(customer_2, commodity_3, "purchase", map[string]any{"trx_count": 1, "trx_amount": 277})
	engine.AddEdge(customer_2, commodity_4, "purchase", map[string]any{"trx_count": 1, "trx_amount": 276})
	engine.AddEdge(customer_2, commodity_5, "purchase", map[string]any{"trx_count": 1, "trx_amount": 294})
	engine.AddEdge(customer_2, commodity_6, "purchase", map[string]any{"trx_count": 1, "trx_amount": 256})
	engine.AddEdge(customer_2, commodity_11, "purchase", map[string]any{"trx_count": 2, "trx_amount": 261})
	engine.AddEdge(customer_2, commodity_12, "purchase", map[string]any{"trx_count": 1, "trx_amount": 304})
	engine.AddEdge(customer_2, commodity_14, "purchase", map[string]any{"trx_count": 1, "trx_amount": 263})
	engine.AddEdge(customer_2, commodity_16, "purchase", map[string]any{"trx_count": 1, "trx_amount": 263})
	engine.AddEdge(customer_2, commodity_21, "purchase", map[string]any{"trx_count": 2, "trx_amount": 284})
	engine.AddEdge(customer_2, commodity_22, "purchase", map[string]any{"trx_count": 1, "trx_amount": 233})
	engine.AddEdge(customer_3, commodity_3, "purchase", map[string]any{"trx_count": 2, "trx_amount": 501})
	engine.AddEdge(customer_3, commodity_4, "purchase", map[string]any{"trx_count": 1, "trx_amount": 435})
	engine.AddEdge(customer_3, commodity_5, "purchase", map[string]any{"trx_count": 1, "trx_amount": 455})
	engine.AddEdge(customer_3, commodity_9, "purchase", map[string]any{"trx_count": 1, "trx_amount": 485})
	engine.AddEdge(customer_3, commodity_14, "purchase", map[string]any{"trx_count": 2, "trx_amount": 464})
	engine.AddEdge(customer_3, commodity_15, "purchase", map[string]any{"trx_count": 1, "trx_amount": 469})
	engine.AddEdge(customer_3, commodity_16, "purchase", map[string]any{"trx_count": 1, "trx_amount": 465})
	engine.AddEdge(customer_3, commodity_17, "purchase", map[string]any{"trx_count": 1, "trx_amount": 459})
	engine.AddEdge(customer_3, commodity_20, "purchase", map[string]any{"trx_count": 1, "trx_amount": 470})
	engine.AddEdge(customer_3, commodity_21, "purchase", map[string]any{"trx_count": 1, "trx_amount": 477})
	engine.AddEdge(customer_4, commodity_1, "purchase", map[string]any{"trx_count": 5, "trx_amount": 551})
	engine.AddEdge(customer_4, commodity_2, "purchase", map[string]any{"trx_count": 1, "trx_amount": 557})
	engine.AddEdge(customer_4, commodity_7, "purchase", map[string]any{"trx_count": 2, "trx_amount": 544})
	engine.AddEdge(customer_4, commodity_9, "purchase", map[string]any{"trx_count": 1, "trx_amount": 578})
	engine.AddEdge(customer_4, commodity_10, "purchase", map[string]any{"trx_count": 1, "trx_amount": 532})
	engine.AddEdge(customer_4, commodity_11, "purchase", map[string]any{"trx_count": 1, "trx_amount": 558})
	engine.AddEdge(customer_4, commodity_14, "purchase", map[string]any{"trx_count": 1, "trx_amount": 557})
	engine.AddEdge(customer_4, commodity_15, "purchase", map[string]any{"trx_count": 1, "trx_amount": 599})
	engine.AddEdge(customer_4, commodity_17, "purchase", map[string]any{"trx_count": 2, "trx_amount": 564})
	engine.AddEdge(customer_5, commodity_5, "purchase", map[string]any{"trx_count": 1, "trx_amount": 1058})
	engine.AddEdge(customer_5, commodity_6, "purchase", map[string]any{"trx_count": 1, "trx_amount": 1101})
	engine.AddEdge(customer_5, commodity_22, "purchase", map[string]any{"trx_count": 1, "trx_amount": 1091})
	engine.AddEdge(customer_6, commodity_1, "purchase", map[string]any{"trx_count": 1, "trx_amount": 336})
	engine.AddEdge(customer_6, commodity_2, "purchase", map[string]any{"trx_count": 2, "trx_amount": 346})
	engine.AddEdge(customer_6, commodity_4, "purchase", map[string]any{"trx_count": 1, "trx_amount": 348})
	engine.AddEdge(customer_6, commodity_6, "purchase", map[string]any{"trx_count": 2, "trx_amount": 397})
	engine.AddEdge(customer_6, commodity_7, "purchase", map[string]any{"trx_count": 1, "trx_amount": 365})
	engine.AddEdge(customer_6, commodity_9, "purchase", map[string]any{"trx_count": 1, "trx_amount": 363})
	engine.AddEdge(customer_6, commodity_10, "purchase", map[string]any{"trx_count": 2, "trx_amount": 351})
	engine.AddEdge(customer_6, commodity_16, "purchase", map[string]any{"trx_count": 2, "trx_amount": 363})
	engine.AddEdge(customer_6, commodity_18, "purchase", map[string]any{"trx_count": 1, "trx_amount": 345})
	engine.AddEdge(customer_6, commodity_19, "purchase", map[string]any{"trx_count": 2, "trx_amount": 393})
	engine.AddEdge(customer_6, commodity_22, "purchase", map[string]any{"trx_count": 1, "trx_amount": 369})
	engine.AddEdge(customer_6, commodity_23, "purchase", map[string]any{"trx_count": 2, "trx_amount": 384})
	engine.AddEdge(customer_7, commodity_1, "purchase", map[string]any{"trx_count": 2, "trx_amount": 312})
	engine.AddEdge(customer_7, commodity_6, "purchase", map[string]any{"trx_count": 1, "trx_amount": 350})
	engine.AddEdge(customer_7, commodity_7, "purchase", map[string]any{"trx_count": 1, "trx_amount": 352})
	engine.AddEdge(customer_7, commodity_12, "purchase", map[string]any{"trx_count": 1, "trx_amount": 393})
	engine.AddEdge(customer_7, commodity_13, "purchase", map[string]any{"trx_count": 2, "trx_amount": 361})
	engine.AddEdge(customer_7, commodity_14, "purchase", map[string]any{"trx_count": 1, "trx_amount": 342})
	engine.AddEdge(customer_7, commodity_15, "purchase", map[string]any{"trx_count": 1, "trx_amount": 364})
	engine.AddEdge(customer_7, commodity_16, "purchase", map[string]any{"trx_count": 1, "trx_amount": 365})
	engine.AddEdge(customer_7, commodity_22, "purchase", map[string]any{"trx_count": 2, "trx_amount": 361})
	engine.AddEdge(customer_8, commodity_5, "purchase", map[string]any{"trx_count": 2, "trx_amount": 235})
	engine.AddEdge(customer_8, commodity_7, "purchase", map[string]any{"trx_count": 1, "trx_amount": 258})
	engine.AddEdge(customer_8, commodity_8, "purchase", map[string]any{"trx_count": 1, "trx_amount": 243})
	engine.AddEdge(customer_8, commodity_9, "purchase", map[string]any{"trx_count": 1, "trx_amount": 270})
	engine.AddEdge(customer_8, commodity_10, "purchase", map[string]any{"trx_count": 2, "trx_amount": 235})
	engine.AddEdge(customer_8, commodity_13, "purchase", map[string]any{"trx_count": 1, "trx_amount": 261})
	engine.AddEdge(customer_8, commodity_15, "purchase", map[string]any{"trx_count": 1, "trx_amount": 261})
	engine.AddEdge(customer_8, commodity_17, "purchase", map[string]any{"trx_count": 2, "trx_amount": 243})
	engine.AddEdge(customer_8, commodity_18, "purchase", map[string]any{"trx_count": 1, "trx_amount": 274})
	engine.AddEdge(customer_8, commodity_20, "purchase", map[string]any{"trx_count": 1, "trx_amount": 239})
	engine.AddEdge(customer_8, commodity_21, "purchase", map[string]any{"trx_count": 1, "trx_amount": 202})
	engine.AddEdge(customer_8, commodity_22, "purchase", map[string]any{"trx_count": 1, "trx_amount": 259})
	engine.AddEdge(customer_8, commodity_23, "purchase", map[string]any{"trx_count": 2, "trx_amount": 250})
	engine.AddEdge(customer_9, commodity_1, "purchase", map[string]any{"trx_count": 1, "trx_amount": 436})
	engine.AddEdge(customer_9, commodity_4, "purchase", map[string]any{"trx_count": 1, "trx_amount": 379})
	engine.AddEdge(customer_9, commodity_5, "purchase", map[string]any{"trx_count": 1, "trx_amount": 397})
	engine.AddEdge(customer_9, commodity_7, "purchase", map[string]any{"trx_count": 1, "trx_amount": 394})
	engine.AddEdge(customer_9, commodity_12, "purchase", map[string]any{"trx_count": 1, "trx_amount": 393})
	engine.AddEdge(customer_9, commodity_13, "purchase", map[string]any{"trx_count": 2, "trx_amount": 423})
	engine.AddEdge(customer_9, commodity_16, "purchase", map[string]any{"trx_count": 1, "trx_amount": 396})
	engine.AddEdge(customer_9, commodity_17, "purchase", map[string]any{"trx_count": 1, "trx_amount": 391})
	engine.AddEdge(customer_9, commodity_19, "purchase", map[string]any{"trx_count": 2, "trx_amount": 453})
	engine.AddEdge(customer_9, commodity_23, "purchase", map[string]any{"trx_count": 1, "trx_amount": 428})
	engine.AddEdge(customer_10, commodity_3, "purchase", map[string]any{"trx_count": 1, "trx_amount": 267})
	engine.AddEdge(customer_10, commodity_5, "purchase", map[string]any{"trx_count": 2, "trx_amount": 289})
	engine.AddEdge(customer_10, commodity_6, "purchase", map[string]any{"trx_count": 1, "trx_amount": 274})
	engine.AddEdge(customer_10, commodity_9, "purchase", map[string]any{"trx_count": 2, "trx_amount": 283})
	engine.AddEdge(customer_10, commodity_10, "purchase", map[string]any{"trx_count": 1, "trx_amount": 266})
	engine.AddEdge(customer_10, commodity_12, "purchase", map[string]any{"trx_count": 1, "trx_amount": 276})
	engine.AddEdge(customer_10, commodity_13, "purchase", map[string]any{"trx_count": 2, "trx_amount": 286})
	engine.AddEdge(customer_10, commodity_15, "purchase", map[string]any{"trx_count": 3, "trx_amount": 291})
	engine.AddEdge(customer_10, commodity_16, "purchase", map[string]any{"trx_count": 1, "trx_amount": 280})
	engine.AddEdge(customer_10, commodity_17, "purchase", map[string]any{"trx_count": 1, "trx_amount": 284})
	engine.AddEdge(customer_10, commodity_20, "purchase", map[string]any{"trx_count": 1, "trx_amount": 281})
	engine.AddEdge(customer_10, commodity_22, "purchase", map[string]any{"trx_count": 1, "trx_amount": 284})
	engine.AddEdge(customer_10, commodity_23, "purchase", map[string]any{"trx_count": 1, "trx_amount": 279})
}
